# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title
permalink: /:categories/:title
future: true
safe: true
lsi: false

include: [.htacces]
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "sass"]
keep_files: ['.git']
timezone: Europe/London
pygments: true

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Salsa Caribe
tagline: Learn to dance Cuban Salsa!
vcard :
  name : Salsa Caribe productions
  email : salsacaribe@aol.com
  phone :
    human: '07958 102188'
    machine: '+447958102188'
  # github : salsacaribecouk
  twitter : salsacaribecouk
  # feedburner : feedname
events :
  - monday
  - saturday
  - sunday
navigation:
  - text: Home
    url: /index.html
  - text: News
    url: /news
  - text: Classes
    url: /classes
  - text: Club nights
    url: /club-nights
  - text: About
    url: /about
  - text: Contact
    url: /contact

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
# production_url : http://salsacaribecouk.github.com

textile: RedCloth
markdown : kramdown
kramdown:
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

plugins: ./_plugins
# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
